# Data parameters
data:
  seed: 777
  train_data_path: '~/.pytorch/PLACES365_data/train'
  val_data_path: '~/.pytorch/PLACES365_data/val'
  download: True
  batch_size: 2048
  shuffle: True
  drop_last: True
  download: True
  num_workers: 4
  img_size: [64, 64]

# Model parameters
model:
  in_img: [3, 64, 64]
  out_dim: 365
  patch_size: 16
  layers: 12
  emb_size: 768
  d_ff: 3072
  num_heads: 12
  drop_rate: 0.1

# Training parameters
train:
  epochs: 300
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 0.00000001
  weight_decay: 0.01

# Save
save:
  model_name: 'places365'

# Other parameters
others:
  log_period: 8