# Data parameters
data:
  seed: 777
  data_path: '~/.pytorch/CIFAR_data/'
  download: True
  batch_size: 512
  shuffle: True
  drop_last: True
  download: True
  num_workers: 4
  img_size: [32, 32]

# Model parameters
model:
  in_img: [3, 32, 32]
  out_dim: 10
  patch_size: 16
  layers: 12
  emb_size: 768
  d_ff: 3072
  num_heads: 12
  drop_rate: 0.1

# Training parameters
train:
  epochs: 300
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 0.00000001
  weight_decay: 0.01

# Save
save:
  model_name: 'cifar10'

# Other parameters
others:
  log_period: 8